[package]
name = "htvmm"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = { version = "0.8.2", default-features = false }
x86_64 = "0.14.10"
linked_list_allocator = "0.10.4"

common = { path = "../common" }

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cc = "1.0.73"
